# -*- coding: utf-8 -*-
{
    'name': u'Cortex Project',
    'version': '11.0',
    'category': 'Cortex',
    'summary': 'Project Management',
    'website': 'http://www.cortexna.com',
    'description': u"""


This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.

""",
    'author': u'Cortex',
    'depends': [
        'project', 'purchase', 'sale','cortex_na'
    ],

    'data': [

        'views/project_view.xml',
        'views/purchase_order_view.xml',
        'views/sale_order_view.xml',
        'views/hide_menu.xml',

    ],
    'qweb': [
    ],

    'application': False,
    'license': u'OPL-1',
    'auto_install': False,
    'installable': True,
}
